const user=JSON.parse(localStorage.getItem('session')||'null');
if(!user||user.role!=='admin') location.href='/login.html';
async function loadStats(){const r=await fetch('/api/stats');const d=await r.json();stats.innerHTML=`<div class="stat">Students<b>${d.students}</b></div><div class="stat">Companies<b>${d.companies}</b></div><div class="stat">DSA Searches<b>${d.students+d.companies}</b></div><div class="stat">System<b>Active</b></div>`;}
async function loadCompanies(){const r=await fetch('/api/companies');const d=await r.json();companyList.innerHTML=d.companies.map(c=>`<div class="company-card"><button class="danger" onclick="deleteCompany('${c.id}')">Delete</button><h3>${c.name}</h3><b>${c.role}</b><p>CGPA ${c.minCGPA} | ${c.location} | ${c.pkg}</p><p>${c.requiredSkills.join(', ')}</p></div>`).join('');companySelect.innerHTML=d.companies.map(c=>`<option value="${c.id}">${c.name} - ${c.role}</option>`).join('');}
async function addCompany(){
 const body={name:cname.value,role:role.value,description:desc.value,minCGPA:mincgpa.value,requiredSkills:reqskills.value,requiredTraining:reqtraining.value||'None',requiredInternship:reqinternship.value||'None',location:location.value,pkg:package.value,deadline:deadline.value};
 const r=await fetch('/api/company/add',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();companyMsg.textContent=d.message;if(d.success){companyForm.reset();loadCompanies();loadStats();}
}
async function deleteCompany(id){if(!confirm('Delete this company?'))return;const r=await fetch('/api/company/delete?id='+encodeURIComponent(id),{method:'POST'});const d=await r.json();alert(d.message);loadCompanies();loadStats();}
async function loadStudents(){const q=encodeURIComponent(studentSearch.value);const min=minFilter.value;const r=await fetch('/api/students?q='+q+'&minCGPA='+encodeURIComponent(min));const d=await r.json();studentList.innerHTML=d.students.map(s=>`<div class="student-card"><b>${s.id} - ${s.name}</b><p>${s.branch} | CGPA ${s.cgpa} | ${s.skills.join(', ')}</p><p class="small">Training: ${s.training.join(', ')} | Internship: ${s.internships.join(', ')}</p></div>`).join('')||'<p>No students found.</p>';}
async function matchCandidates(){const id=companySelect.value;const r=await fetch('/api/match-all?company='+encodeURIComponent(id));const d=await r.json();matchResults.innerHTML=d.results.map((x,i)=>`<div class="match-card"><b>#${i+1} ${x.name}</b> — ${x.branch} — CGPA ${x.cgpa}<p>Skill similarity: <span class="score">${x.similarity}%</span></p><div class="bar"><div style="width:${x.similarity}%"></div></div><p>Matched skills: ${x.matchedSkills.join(', ')||'None'}</p></div>`).join('')||'<p>No students satisfy all requirements.</p>';}
async function loadApplications(){const status=encodeURIComponent(applicationFilter.value);const r=await fetch('/api/applications?status='+status);const d=await r.json();applicationList.innerHTML=d.applications.map(a=>`<div class="student-card"><b>${a.id} - ${a.studentName}</b><p>${a.companyName} - ${a.role} | Match ${a.score}% | <span class="tag">${a.status}</span></p><button class="btn btn-outline" onclick="changeApplication('${a.id}','APPROVED')">Approve</button> <button class="btn btn-outline" onclick="rejectApplication('${a.id}')">Reject</button><select onchange="changeApplication('${a.id}',this.value)"><option value="">Move to...</option><option>SHORTLISTED</option><option>INTERVIEW</option><option>SELECTED</option><option>NOT_SELECTED</option></select><div class="message-box"><input id="message-${a.id}" placeholder="Write a message for ${a.studentName}"><button class="btn btn-primary" onclick="sendStudentMessage('${a.studentId}','${a.id}')">Send Message</button><p id="message-status-${a.id}" class="message"></p></div></div>`).join('')||'<p>No applications.</p>';}
async function changeApplication(id,status,remark=''){const r=await fetch('/api/application/status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({applicationId:id,status,remark})});const d=await r.json();alert(d.message);loadApplications();loadStats();}
function rejectApplication(id){const remark=prompt('Rejection reason:');if(remark)changeApplication(id,'REJECTED',remark);}
async function sendStudentMessage(studentId,applicationId){const input=document.getElementById('message-'+applicationId);const status=document.getElementById('message-status-'+applicationId);const message=input.value.trim();if(!message){status.textContent='Enter a message first.';return;}const r=await fetch('/api/notifications/send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({recipient:studentId,message})});const d=await r.json();status.textContent=d.message;if(d.success)input.value='';}
async function addDrive(){const body={company:driveCompany.value,role:driveRole.value,date:driveDate.value,venue:driveVenue.value,openings:driveOpenings.value,deadline:driveDeadline.value,requirements:driveRequirements.value};const r=await fetch('/api/drive/add',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(d.success){driveForm.reset();loadDrives();}else alert(d.message);}
async function loadDrives(){const r=await fetch('/api/drives');const d=await r.json();driveList.innerHTML=d.drives.map(x=>`<div class="company-card"><b>${x.company} - ${x.role}</b><p>${x.date} | ${x.venue} | ${x.openings} openings</p></div>`).join('');}
function logout(){localStorage.removeItem('session');location.href='/login.html'}
loadStats();loadCompanies();loadStudents();loadApplications();loadDrives();
